variables:
  IMAGE_TAG_RELEASE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
- deploy

build-dev:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - echo "building push-server"
    - docker build -t $CI_REGISTRY_IMAGE:push-server ./push-server
    - docker push $CI_REGISTRY_IMAGE:push-server
    - echo "building php7.4-node"
    - docker build -t $CI_REGISTRY_IMAGE:php7.4 ./php-7.4-node
    - docker push $CI_REGISTRY_IMAGE:php7.4
    - echo "building php7.4-node12"
    - docker build -t $CI_REGISTRY_IMAGE:php7.4-node12 ./php-7.4-node12
    - docker push $CI_REGISTRY_IMAGE:php7.4-node12
    - echo "building php8.0-node12"
    - docker build -t $CI_REGISTRY_IMAGE:php8.0-node12 ./php-8.0-node12
    - docker push $CI_REGISTRY_IMAGE:php8.0-node12
    - echo "building php8.1-node-18"
    - docker build -t $CI_REGISTRY_IMAGE:php8.1-node18 ./php-8.1-node18
    - docker push $CI_REGISTRY_IMAGE:php8.1-node18

